### ISSUE TITLE
Add more detailed documentation for v2.0.0 docker options and browser APIs

### ISSUE THREAD

**Issue by x0day** [browserless/browserless#3637]
I seen some environment variable was deprecated, but I can't find any details about this.

eg : `DEFAULT_LAUNCH_ARGS` `FUNCTION_ENABLE_INCOGNITO_MODE` `FUNCTION_EXTERNALS`

**Comment by x0day** [comment]
Any plan to publish new version docs at browserless.io?

**Comment by jimmyfive** [comment]
Have you seen this one?
https://github.com/browserless/browserless/blob/main/MIGRATION-2.0.md

**Comment by joelgriffith** [comment]
We're working on a plan to incorporate v2.0 docs into our docsite, however it's a big task so it might be a while to fully encompass v1 and v2 together. For now, the best resources are that Migration doc + the docs that come embedded in the container.
