### ISSUE TITLE
No handler or file found for resource /content - GKE deployment

### ISSUE THREAD

**Issue by jimmyfive** [browserless/browserless#3638]
**Describe the bug**
I'm using the latest docker container in a GKE deployment (ghcr.io/browserless/multi). 
The /screenshot endpoint is working properly, however the /content I get:
No handler or file found for resource /content

**To Reproduce**
1. Created a deployment in GCP GKE, just like I've done in Browserless v.1.
2. Launched deployment.
3. Tested /screenshot + /playwright/chromium. Worked as designed.
4. Tested /content and I see the error.

Log from Browserless:
Browserless:server No matching WebSocket route handler for "http://0.0.0.0:3000/content?token=6782a5ff-1ca0-48e4-96ee-d643b49ed8eb

![Screenshot 2023-11-01 152124](https://github.com/browserless/browserless/assets/5302614/295187fc-5524-43f5-90de-348fa1a43fe5)

**Comment by jimmyfive** [comment]
Same behavior noticed in Docker.

**Comment by joelgriffith** [comment]
@jimmyfive what's the conten-type header you're sending? V2 is a bit more strict about content-types matching. Locally on `latest` this works for me:

```sh
curl --request POST \
  --url 'http://localhost:3000/content?token=6R0W53R135510' \
  --header 'Content-Type: application/json' \
  --data '{
	"url": "https://example.com/"
}'
```

**Comment by jimmyfive** [comment]
Hey, I found the problem.  Your question pointed me in the right direction.  There was a left over "Accept" header from my /screenshot template that caused that error.  The content-type header was correct.
Strange that it would fail with a page not found and that "No matching WebSocket route handler for <URL>".

**Comment by joelgriffith** [comment]
Yeah that does not strike me well either. I'll see what we can do to help with the messaging here.

**Comment by masterwishx** [comment]
Also have same issue ,cant access to debugger (browserless) itselt
