### ISSUE TITLE
Inconsistent Docker Images

### ISSUE THREAD

**Issue by TheSwerik** [browserless/browserless#3650]
**Describe the bug**
The Docker Image `ghcr.io/browserless/chrome` does behave very differently compared to `browserless/chrome`.
This might be intended but is very confusing because the GitHub Readme recommends using `ghcr.io/browserless/chrome` while the website recommends using `browserless/chrome`.

**To Reproduce**
1. run `docker run -p 3000:3000 ghcr.io/browserless/chrome`
2. run `docker run -p 3001:3000 browserless/chrome`
3. compare

**Expected behavior**
I expected both to behave the same or the Readme, Website or Docs to mention which one I should be using.

**Screenshots**
![Logging Example](https://github.com/browserless/browserless/assets/47034061/bef32820-dc77-43da-a2fb-9a0458873b13)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Differences I immediately noticed:
- Logging looking completely different
- Playwright URL is `/playwright/chromium` for `ghcr.io/browserless/chrome` and `/playwright` for `browserless/chrome`
- `/docs` is the full documentation in `ghcr.io/browserless/chrome` and a swagger doc in`browserless/chrome`

**Comment by andyMrtnzP** [comment]
Yeah, this is intended. Unfortunately, we still need to thoroughly update our docs and deprecate the current Docs site, since it cover v1 exclusively. Sorry for the inconvenience, we will add a deprecation notice in short

**Comment by joelgriffith** [comment]
Agreed with @andyMrtnzP : in short V2 is an entire rewrite to support more browsers, extensions and more. We do have notices in README's as well as migration docs to help. We also mention in our README that the hosted service we provide is still on V1 but V2 is coming soon as an option.

Feedback here is great, and we'll utilize this for updating our docsite as well.
