### ISSUE TITLE
After moved from v1.61 to v2.0 cant access to browserless WebUI

### ISSUE THREAD

**Issue by masterwishx** [browserless/browserless#3667]
Using Docker in Unraid

Moved from latest `browserless/chrome v1.61` to `ghcr.io/browserless/chrome v2.0`

After that cant access to Browserless Page in chrome by http://192.168.0.199:3007/?token=xxxxxxxxxxxxx like worked Befor.

![image](https://github.com/browserless/browserless/assets/28630321/095b002e-bff4-44a5-aca2-459ce9906ed0)
![image](https://github.com/browserless/browserless/assets/28630321/9dbde46c-56a3-4bea-9226-28626601598d)

**Comment by masterwishx** [comment]
![image](https://github.com/browserless/browserless/assets/28630321/08752e89-daa5-4be0-87b7-980c59fa4325)

**Comment by methaqualon** [comment]
> ![image](https://user-images.githubusercontent.com/28630321/282223433-08752e89-daa5-4be0-87b7-980c59fa4325.png)

так там путь и вовсе другой для девтулс.
http://[localhost]:[port]/devtools/inspector.html?ws=[host]:[port]/devtools/page/[sessionid]
другой вопрос что у тебя и корень не работает. Значит на этом айпи и порту определенно ничего и не сидит.
Если забиндился по 0.0.0.0 то проблема может быть в самой сети, так что следует проверить локалхост, если тачка другая - с нее же курлом, не знаю что там именно унрейд позволяет и что из себя вообще представляет.
Если это все не помогло - может быть связано с моей проблемой, симптомы похожи

**Comment by masterwishx** [comment]
> Если это все не помогло - может быть связано с моей проблемой, симптомы похожи

In v1.63 have no problem, using custom network in Unraid
I think I had same problem sometime in v1. X but then it was fixed...

**Comment by masterwishx** [comment]
> так там путь и вовсе другой для девтулс.

Sorry, first picture from when i tryed some other ways ,but the problem is in `http://192.168.0.199:3007/?token=xxxxxxxxxxxxx`

**Comment by masterwishx** [comment]
im using custom network in Unraid `172.18.0.35:3000/TCP <-> 192.168.0.199:3012`

**Comment by masterwishx** [comment]
> другой вопрос что у тебя и корень не работает. Значит на этом айпи и порту определенно ничего и не сидит.

but other *.js is loaded

**Comment by methaqualon** [comment]
> > другой вопрос что у тебя и корень не работает. Значит на этом айпи и порту определенно ничего и не сидит.
> 
> but other *.js is loaded
из кеша
или как, сервер отдал 404, но скриптов сверху левых докинул?
в остальном я и сам не в курсе, в моём issue тоже нелогичное поведение описывается

**Comment by masterwishx** [comment]
> из кеша
> или как, сервер отдал 404, но скриптов сверху левых докинул?

Those scripts from the program itself, also I have no cache in dev settings

**Comment by masterwishx** [comment]
> или как, сервер отдал 404, но скриптов сверху левых докинул?

you was right , *js its chrome extensions ...

**Comment by masterwishx** [comment]
Checked `http://192.168.0.199:3012/config?token=xxxxx` and `http://192.168.0.199:3012/docs` are working OK
Also found much less size of container v2.0 than v1.6 : 

![image](https://github.com/browserless/browserless/assets/28630321/cb3625c2-fd1d-42a1-8b4e-c2bd362a6f55)

**Comment by andyMrtnzP** [comment]
Do you mean the live debugger? This: 

![image](https://github.com/browserless/browserless/assets/93541085/85b79844-5695-47f9-a093-66707ce57c81)

If that's the case, v2 doesn't bundle the debugger. But you can clone [the debugger repo](https://github.com/browserless/debugger) and use it with v2 (don't forget to add the API key on the debugger)

**Comment by masterwishx** [comment]
> Do you mean the live debugger? This:

Yes

**Comment by masterwishx** [comment]
> If that's the case, v2 doesn't bundle the debugger. But you can clone [the debugger repo](https://github.com/browserless/debugger) and use it with v2 (don't forget to add the API key on the debugger)

Oh ,got it , i cant use it in docker ?

**Comment by joelgriffith** [comment]
It's not yet available in v2.0.0 just yet, but we will incorporate it soon!

**Comment by masterwishx** [comment]
> It's not yet available in v2.0.0 just yet, but we will incorporate it soon!

Thanks Waiting ...

**Comment by geminigeek** [comment]
> It's not yet available in v2.0.0 just yet, but we will incorporate it soon!

hi
any update on debugger ?

**Comment by masterwishx** [comment]
> It's not yet available in v2.0.0 just yet, but we will incorporate it soon!

any news about live debugger?

**Comment by masterwishx** [comment]
> It's not yet available in v2.0.0 just yet, but we will incorporate it soon!

any news ?
