### ISSUE TITLE
Different version of chrome results in forever hanging browser.connect()

### ISSUE THREAD

**Issue by Milen-Minchev** [browserless/browserless#3669]
Hey, good job for putting such a useful package out!

I find it very useful and life saver, but I faced a problem when using puppeteer, where your chrome version is not updated to the lates required by them.

With lates puppeteer:  Puppeteer v21.5.0 - chrome version 119.0.6045.105 is required. but yours is 113.0.5672.63 which is resulting in hanging on browser.connect() forever.

As a workaround I've installed Puppeteer v20.1.0, but I assume it will be good if we are running the lates version.

Thank you and keep up the good work!

**Comment by joelgriffith** [comment]
Hey there! This is actually resoled as of today, so going to close. Just checked with puppeteer 21.5.0 (Chrome/118.0.5993.70 running in the cloud)
