### ISSUE TITLE
Adding a bottom margin/padding when printing to PDF

### ISSUE THREAD

**Issue by curtiswmcmillin** [browserless/browserless#3684]
**Describe the bug**
When calling IPage.PdfDataAsync, a bottom margin/padding is being added:
![image](https://github.com/browserless/browserless/assets/12774998/cfb35efb-dab5-4de1-93ed-895a91415e98)
This started a few days ago, on 11/13, around 6PM EST.

**To Reproduce**
Use attached HTML to test and observe the behavior.
[html.zip](https://github.com/browserless/browserless/files/13395041/html.zip)

**Expected behavior**
The footer should align directly against the bottom of the page:
![image](https://github.com/browserless/browserless/assets/12774998/5a6efba2-d510-4d0f-b14c-ded6c75147d9)

**Screenshots**
Bad:
![image](https://github.com/browserless/browserless/assets/12774998/cfb35efb-dab5-4de1-93ed-895a91415e98)
Good:
![image](https://github.com/browserless/browserless/asset

s/12774998/16fd3092-1591-45f1-9d43-f6d440a3b7ed)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 119.0.6045.160 (Official Build) (64-bit 

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by joelgriffith** [comment]
@curtiswmcmillin  are you observing this in our hosted cloud?

**Comment by curtiswmcmillin** [comment]
yes

**Comment by curtiswmcmillin** [comment]
@joelgriffith Apologies, I forgot to attach the HTML (html.zip)
