### ISSUE TITLE
(Browserless V2) Error when using browser.close

### ISSUE THREAD

**Issue by Hackatosh** [browserless/browserless#3727]
**Describe the bug**
I try to print many PDF (30) at the same time using `puppeteer.connect` and then `page.createPDFStream`. When I have finished to create my PDFs and I use browser.close(), I encounter the following error : `Error: This socket has been ended by the other party`.
No error is not encountered if I use `browser.disconnect()`.

**To Reproduce**
Try to print many PDF (30) at the same time using `puppeteer.connect` and then `page.createPDFStream` and the close the browser `using browser.close`

**Expected behavior**
I do not expect to be any error. Or maybe the documentation is outdated and I should use `browser.disconnect` and not `browser.close` ?

**Screenshots**

![image](https://github.com/browserless/browserless/assets/37976573/04dcc8c1-a76a-4c4a-a9ce-8fcd41116990)

**Desktop :**
 - I use the image ghcr.io/browserless/chrome:latest

**Comment by joelgriffith** [comment]
Interesting, thanks for raising. The `writeAfterFIN` error has surfaced a few times prior, and is generally benign. I'll see if we can patch this into more of a warning and not an error-level
