### ISSUE TITLE
[Browserless 2.0] Clarification on the "embedded" API (to record the page with audio)

### ISSUE THREAD

**Issue by joris** [browserless/browserless#3747]
The Migration-2.0 guide explains [that the /screencast API has been removed in favor of a library-based approach, through what you call an "embedded" API.](https://github.com/browserless/browserless/blob/main/MIGRATION-2.0.md#screencast)

I’m specifically looking to record the browser including audio, so I was super excited to read that with 2.0 it’s possible “to initiate a recording of a page and get the response back (with audio!)”.

But there are no further details about the "embedded" API and how to use it. I’ve also checked the built-in docs site that’s part of the 2.0 beta.

Got any pointers?

**Comment by joelgriffith** [comment]
Good catch, definitely something we need to address in our embedded docsite. Will get this addressed -- thanks for raising!

**Comment by joelgriffith** [comment]
Good catch, definitely something we need to address in our embedded docsite. Will get this addressed -- thanks for raising!

**Comment by joelgriffith** [comment]
Sadly going to have to close this one as a "won't fix." The screencasting feature is now supported in some/most libraries and we aren't doing anything groundbreaking here, and it's also widely detectable as automated traffic. Sorry folks :/

**Comment by joris** [comment]
@joelgriffith ah so no audio recording in Browserless?
