### ISSUE TITLE
The PDF is blank when downloaded

### ISSUE THREAD

**Issue by Richieyukio** [browserless/browserless#3762]
the url is https://axloqawkdri.feishu.cn/wiki/JXTDwbsvGi32aAkv24Tc8e6vn32, when i use /pdf to download is blank.

**Comment by joelgriffith** [comment]
All I get is a QR code with that site -- is there a login action that needs to happen prior?

**Comment by Richieyukio** [comment]
hello,Please make sure that the URL you are using is [https://axloqawkdri.feishu.cn/wiki/JXTDwbsvGi32aAkv24Tc8e6vn32](https://axloqawkdri.feishu.cn/wiki/JXTDwbsvGi32aAkv24Tc8e6vn32)

**Comment by joelgriffith** [comment]
They have the following CSS when printing:


```@media print
body {
    display: none !important;
}
```

You'll need to override this rule with injecting your own CSS or removing that CSS snippet in their HTML.
