### ISSUE TITLE
Small mistake in split operation for userDataDir in version 2

### ISSUE THREAD

**Issue by peacemaker123456** [browserless/browserless#3768]
Small mistake in split operation for userDataDir

const manualUserDataDir =
      launchOptions.args
        ?.find((arg) => arg.includes('--user-data-dir='))
        ?.split('=')[2] || (launchOptions as CDPLaunchOptions).userDataDir;

Simply change ?.split('=')[2] to ?.split('=')[1]

Then the first way of passing userDataDir will also work

**Comment by joelgriffith** [comment]
Thanks for raising! PR incoming...
