### ISSUE TITLE
[v2] debugger "Current Sessions" can not get session

### ISSUE THREAD

**Issue by broven** [browserless/browserless#3801]
**Describe the bug**
`/sessions` is blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
**To Reproduce**
1. run a browserless chrome container
2. start a browserless/debugger
3. change `Browser URL` from 'Debugger Settings' to your browserless instance, eg: ws://192.168.100.64:3001

**Expected behavior**
`/session` should set `access-control-allow-origin: *` to response header

**Screenshots**
![image](https://github.com/browserless/browserless/assets/12854613/f7ee627d-c94c-490f-9d74-dc4971c22d4e)
![image](https://github.com/browserless/browserless/assets/12854613/b36878e6-b230-4f98-852c-952c3f33a876)

**Comment by joelgriffith** [comment]
We don’t have CORS headers set in V2 by default but you can turn it on. It’s an env variable which you can see in src/config.ts

**Comment by joelgriffith** [comment]
Also, when you reply back we should move this over to https://github.com/browserless/browserless/discussions?
