### ISSUE TITLE
[v2] No handler or file found for resource /devtools/inspector.html

### ISSUE THREAD

**Issue by broven** [browserless/browserless#3802]
**Describe the bug**
access devtools: http://browserless.local:3000/devtools/inspector.html?ws=browserless.local:3001/devtools/page/2A495922F530AB1712F13D7F379D5D74
will return  `No handler or file found for resource /devtools/inspector.html`, instead of the devtool
(This address is generate by browserless/debugger)

No handler or file found for resource /devtools/inspector.html
**To Reproduce**
1. run a browserless chrome container
2. start a browserless/debugger
3. change Browser URL from 'Debugger Settings' to your browserless instance, eg: ws://192.168.100.64:3001
4.  click a session from 'Current Sessions' panel

**Expected behavior**
should get the devtool

**Comment by joelgriffith** [comment]
Ah, yeah, V1 does rely on using Chrome's internal inspector which we don't have set up just yet. Nice find.

**Comment by broven** [comment]
How can we attach devtools in v2

**Comment by joelgriffith** [comment]
Should be addressed in https://github.com/browserless/browserless/pull/3847

**Comment by L480** [comment]
DevTools are working now, but my WebSocket connection keeps disconnecting.

**Comment by joelgriffith** [comment]
OK, that issue should be resolved by: https://github.com/browserless/browserless/pull/3853

**Comment by joelgriffith** [comment]
OK, this should be fixed and working (was for me locally). Going to close for now but please re-open if any issues still persist (include any details you can).
