### ISSUE TITLE
Guidance: Are "chrome-stable" docker image tags EOL?

### ISSUE THREAD

**Issue by mattcobb** [browserless/browserless#3805]
yoho!
We have been using a browserless docker image for some years with tags like 1.N-chrome-stable, e.g. [1.60-chrome-stable](https://hub.docker.com/layers/browserless/chrome/1.60-chrome-stable/images/sha256-7db5e3aad20c201abaa03bbbc868a55ef96574cda0e67ccb7e4e032053ecb87d?context=explore)  We noticed with the 1.61 release there was no longer a "chrome-stable" tag.  Is that on purpose or just oversight?  If the chrome-stable variants are going away, what image would you recommend instead?  We prefer to not use "latest", instead pin it to a more specific tag.

**Comment by joelgriffith** [comment]
Hot off the press (For `linux/amd64`): https://hub.docker.com/layers/browserless/chrome/1-chrome-stable/images/sha256-efac47cfff3830d9a50b27d29f8bbb61949058ae336c823fbe9bd3c0d1debcc8?context=repo

**Comment by mattcobb** [comment]
Thank you!
