### ISSUE TITLE
When using chrome instead of chromium : Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by GautierT** [browserless/browserless#3841]
**Describe the bug**

When I use Chrome instead of Chromium (`RUN npx --yes playwright install chrome` in Dockerfile)
And setting executablePath to `/opt/google/chrome/google-chrome`

Their is an error when setting EmbeddedApi : `Execution context was destroyed, most likely because of a navigation.`

I want to use Chrome because when I record a Teams meeting, I can't see the other participant webcam so I want to try if it's related to missing codec in Chromium. (Do you have an other idea ?)

*If your having issues with a particular site or being bot-blocked, then it's
not an issue with this repo. Please send us an email at support@browserless.io.*

**To Reproduce**
1. Install chrome with Playwright instead of chromium in Dockerfile
2. Set executablePath to /opt/google/chrome/google-chrome
3. Run docker
4. Connect puppeteer with : `browserWSEndpoint: 'ws://localhost:3000/?record=true&blockAds=false'`

**Expected behavior**
EmbeddedApi should load correcly

**Additional context**
```
 {
  browserless.io:browsers:cdp:chromium   args: [
  browserless.io:browsers:cdp:chromium     '--remote-debugging-port=41489',
  browserless.io:browsers:cdp:chromium     '--no-sandbox',
  browserless.io:browsers:cdp:chromium     '--autoplay-policy=no-user-gesture-required',
  browserless.io:browsers:cdp:chromium     '--window-size=1920,1080',
  browserless.io:browsers:cdp:chromium     '--ozone-override-screen-size=1920,1080',
  browserless.io:browsers:cdp:chromium     '--user-data-dir=/tmp/browserless-data-dirs/browserless-data-dir-c1cc721a-0cb1-404d-b502-7bad5e2964be',
  browserless.io:browsers:cdp:chromium     '--enable-usermedia-screen-capturing',
  browserless.io:browsers:cdp:chromium     '--enable-blink-features=GetUserMedia',
  browserless.io:browsers:cdp:chromium     '--allow-http-screen-capture',
  browserless.io:browsers:cdp:chromium     '--auto-select-desktop-capture-source=browserless-screencast',
  browserless.io:browsers:cdp:chromium     '--disable-infobars',
  browserless.io:browsers:cdp:chromium     '--load-extension=/usr/src/app/extensions/screencast',
  browserless.io:browsers:cdp:chromium     '--disable-extensions-except=/usr/src/app/extensions/screencast'
  browserless.io:browsers:cdp:chromium   ],
  browserless.io:browsers:cdp:chromium   waitForInitialPage: true,
  browserless.io:browsers:cdp:chromium   stealth: true,
  browserless.io:browsers:cdp:chromium   slowMo: 500,
  browserless.io:browsers:cdp:chromium   channel: 'chrome',
  browserless.io:browsers:cdp:chromium   executablePath: '/opt/google/chrome/google-chrome',
  browserless.io:browsers:cdp:chromium   headless: false,
  browserless.io:browsers:cdp:chromium   ignoreDefaultArgs: [ '--enable-automation' ]
  browserless.io:browsers:cdp:chromium } Launching CDP Chrome Handler
```

Thanks a lot for this awesome library !

**Comment by joelgriffith** [comment]
Thanks for the kind words! We're working on a Chrome-stable build which should be out soon and work just fine. My guess is that there's some flags or library version mis-matches which is giving you the issues you're seeing. I'll keep you posted here when we get a Chrome build out.

**Comment by joelgriffith** [comment]
Can you try this package now? https://github.com/browserless/browserless/pkgs/container/chrome I'd also try without `record` to see if that's what's causing issues.

**Comment by joelgriffith** [comment]
Cool, going to close this out for now. If you encounter issues please let us know by creating a new issue since the circumstances will have changed somewhat significantly
