### ISSUE TITLE
blockAds=true on Firefox

### ISSUE THREAD

**Issue by simion** [browserless/browserless#3845]
Tried `blockAds=true` when using firefox via playwright websocket. It does not load ublock.

I've looked at the [install adblock script](https://github.com/browserless/browserless/blob/main/scripts/install-adblock.js) and it seems it only downloads the chrome extension.

Ublock also has a `.xpi` extension for firefox, second items from "assets": https://api.github.com/repos/gorhill/uBlock/releases/latest

**Comment by simion** [comment]
@joelgriffith i can contribute with this change if you're too busy :D

**Comment by joelgriffith** [comment]
Yup, would happily review/merge a PR if you have the time :)

**Comment by joelgriffith** [comment]
Sadly we did take a look into this and it seems not quite feasible just yet, going to close for now.
