### ISSUE TITLE
browserless/chrome (v1) on Docker Hub is no longer built for ARM64

### ISSUE THREAD

**Issue by L480** [browserless/browserless#3851]
[browserless/chrome:latest](https://hub.docker.com/layers/browserless/chrome/latest/images/sha256-4f01ff422f208679a03c8c24f080b25d2675558c04f4c34c8fd6e89a78db7f9a?context=explore) (v1) on Docker Hub is no longer built for ARM64.

**Comment by joelgriffith** [comment]
Fixed now!
