### ISSUE TITLE
Sharing cache between docker containers

### ISSUE THREAD

**Issue by hurdofdaniel** [browserless/browserless#3868]
I have an app for taking screenshots of webpages before and after rolling out updates to ensure everything is all good and working. I am running it through laravel with browsershot.

I was wondering if there is anyway to cache the cookies, images, css, js etc through the 8 instances that are running in docker. I have tried DEFAULT_USER_DATA_DIR to a path and then using volumes to link that to a path that all containers are using. This doesn't seem to work

Is this not how the DEFAULT_USER_DATA_DIR works and if not, what can I do to somehow share cache?

Thanks,
Daniel

**Comment by joelgriffith** [comment]
@hurdofdaniel you'll need to use something like docker volumes in order to share stateful/file-systems between containers. There's also times that Chrome _can't_ share the same user-data-dir between two processes.
