### ISSUE TITLE
/scrape API - custom behavior with waitFor and dynamical loading page

### ISSUE THREAD

**Issue by macrochel** [browserless/browserless#3872]
I need to make scrape the assortment, but page is loading dynamically. I need to create a function, that will wait when every loadings will finish (on this page there's not just one load)
`{ "url": "https://a201910091655256231033.szwego.com/static/index.html#/shop_detail/A201910091655256231033", "elements": [{"selector": ".word-break, .lazy"}], "waitFor": 10000 }`
Now I can get only 128 items

**Comment by joelgriffith** [comment]
Are you needing to scroll in order to trigger those elements to appear?
