### ISSUE TITLE
"launch.blockAds" is not allowed

### ISSUE THREAD

**Issue by Aubermean** [browserless/browserless#3873]
In 2.2 blockAds doesn't work!

`  browserless.io:server WebSocket query-params contain errors sending 400:"launch.blockAds" is not allowed +2m`

**Comment by joelgriffith** [comment]
`blockAds` is a top-level query-parameter and no longer in launch options. Did you see that mentioned someplace for V2?

```const browser = await puppeteer.connect({
  browserWSEndpoint: `ws://0.0.0.0:3000?blockAds`,
});```

**Comment by Aubermean** [comment]
Hi Joel. No, as far as I can see it isn't mentioned anywhere. Not in the migration .md either. What options are top level and shouldn't be in launch parameters? I haven't found it documented. Thanks!

**Comment by simion** [comment]
@Aubermean you can launch http://localhost:3000/docs after starting browswerless and you'll have yourself a nice up-to-date documentation. All the parameters are documented there.

**Comment by joelgriffith** [comment]
Happy to chat more, but going to close this out for now.
