### ISSUE TITLE
2.2.0: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by Mr-Technician** [browserless/browserless#3879]
**Describe the bug**
When running `docker compose pull` I get a `no matching manifest for linux/arm64/v8 in the manifest list entries` on an Oracle Ampere VM. I am currently running 2.2.0-beta-8 on arm but am unable to pull 2.2.0.

**To Reproduce**
1. Create a arm64 VM
2. Create a docker compose yaml file which pulls the `ghcr.io/browserless/chrome:latest` image
3. See error

**Expected behavior**
`docker compose pull` should pull the arm64 image.

**Screenshots**
![image](https://github.com/browserless/browserless/assets/26885142/1a68e383-baea-44d1-8a1a-920c80353074)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: chrome

**Additional context**
The issue does not occur in my x86 test VM.

**Comment by joelgriffith** [comment]
`ghcr.io/browserless/chrome:latest` isn't supported due to lack of Chrome builds for arm64. I'm guessing you'll likely want `ghcr.io/browserless/chromium:latest`?

**Comment by the-leonat** [comment]
the behaviour changed. before i could also run the `browserless/chrome` docker image without problems.

**Comment by Mr-Technician** [comment]
@joelgriffith I will test the `chromium` image when I am able, but I concur with @the-leonat that the `chrome` image was previously working on arm64.

**Comment by joelgriffith** [comment]
Got it, yup, we were aware of that unfortunate name. We did try our best and captured that detail in the following places:

- https://github.com/browserless/browserless/blob/main/CHANGELOG.md#v220
- https://github.com/browserless/browserless/discussions/3859
