### ISSUE TITLE
Implement Prometheus Metrics format

### ISSUE THREAD

**Issue by Schtil** [browserless/browserless#3892]
**Is your feature request related to a problem? Please describe.**
Yes, the project currently does not support standard monitoring practices. Specifically, the service provides metrics through a continuously expanding JSON array via the /metrics endpoint. This method results in an endlessly growing array which is inefficient and not conducive to standard monitoring and analysis practices.
<br>
**Describe the solution you'd like**
Change the behavior of /metrics - add support for the Prometheus format.
This change would enable the use of standard tools for metrics collection, dashboard creation, and alert setting, thereby enhancing the operability and monitoring capabilities of the service.
<br>

**Describe alternatives you've considered**
Currently, there seems to be no straightforward method to integrate the existing metrics into standard monitoring tools without employing makeshift solutions. One potential workaround could be developing a custom exporter that processes the existing JSON array (possibly by examining the last element) and converts it into a format compatible with Prometheus. However, this approach requires additional overhead and does not address the root problem.
<br>

**Additional context**
Prometheus is a widely adopted standard for metrics collection and monitoring. Supporting this format would align the project with common industry practices and greatly improve its usability for status monitoring and performance analysis.

**Comment by joelgriffith** [comment]
Even though we had rudimentary support for this in V1, it wasn't a great experience as we had several issues come up with what "things" to consider for liveliness, health, and readiness. It's also a deployment-specific technology that not everyone uses, which we're also trying to get away from in open-source. Finally, this is fairly straightforward to implement yourself in the SDK and have _exactly_ what you want. [You can check more out about that here](https://github.com/browserless/browserless/blob/main/bin/scaffold/README.md), and how to use it.

I appreciate the issue, so thank you for taking the time to raise it. At this point I'm going to close this for now as "won't fix".
