### ISSUE TITLE
Kill session by trackingIdnot working

### ISSUE THREAD

**Issue by gleberson-alves** [browserless/browserless#3896]
**Describe the bug**
Kill session by trackingId not working in self hosted version

I've already tested it on several versions, it simply doesn't work.
closing session on kill endpoint passing trackingId does not end the session.
Returns status 204 but the session remains open and running

**Comment by joelgriffith** [comment]
Unfortunately `v1` is nearing end-of-life and we won't be doing work aside from urgent security issues. Going to close.
