### ISSUE TITLE
[BUG] Missing arm64 support for Docker image browserless/chrome:latest

### ISSUE THREAD

**Issue by DaVinci42** [browserless/browserless#3914]
**Describe the bug**
From https://github.com/browserless/browserless/pkgs/container/chrome/188342519?tag=latest
There're 2 supported `OS / Arch`:
- `linux/amd64`
- `unknown/unknown`

**To Reproduce**
```shell
> docker pull ghcr.io/browserless/chrome:latest
latest: Pulling from browserless/chrome
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Expected behavior**
it should support both `amd64` & `arm64`, as this previous image:
```
ghcr.io/browserless/chrome     latest    0e85a7aee4bd   4 weeks ago     2.97GB
```

**Desktop (please complete the following information):**
- Manjaro ARM Linux aarch64
- Macbook Pro, M3 Pro

**Comment by joelgriffith** [comment]
`browserless/chrome` doesn't support arm since there's currently no arm64 builds of Chrome (Stable) for that environment aside from Apple Silicon.
