### ISSUE TITLE
No route or file found for resource GET: /

### ISSUE THREAD

**Issue by wolfdael** [browserless/browserless#3924]
**Describe the bug**
I get the error "No route or file found for resource GET: /" on the docker webui when I access it.

**To Reproduce**
Steps to reproduce the behavior is to use the below docker run command:

docker run
  -d
  --name='browserless'
  --net='bridge'
  -e TZ="Asia/Calcutta"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Marcus"
  -e HOST_CONTAINERNAME="browserless"
  -e 'SCREEN_WIDTH'='2560'
  -e 'SCREEN_HEIGHT'='1440'
  -e 'SCREEN_DEPTH'='16'
  -e 'CONNECTION_TIMEOUT'='300000'
  -e 'ENABLE_DEBUGGER'='false'
  -e 'PREBOOT_CHROME'='true'
  -e 'MAX_CONCURRENT_SESSIONS'='10'
  -e 'CHROME_REFRESH_TIME'='600000'
  -e 'DEFAULT_BLOCK_ADS'='true'
  -e 'DEFAULT_STEALTH'='true'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:3000]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/masterwishx/unraid-templates/main/images/browserless_logo.png'
  -p '3000:3000/tcp'
  --restart=unless-stopped
  --shm-size=2G 'ghcr.io/browserless/chromium:latest'
aa61f95f646f1fe93423cfce33c259cf50cc3d3f4e1bc0436ecf7b60e769c379

**Expected behavior**
webui is visible

**Desktop (please complete the following information):**

- OS: unraid linux docker
- Browser : chrome
- Version : latest

**Comment by Mr-Technician** [comment]
Does the `/docs` path work? I likewise get a similar error at `/` but my instance works normally.

**Comment by joelgriffith** [comment]
We're porting it over for `v2` images soon -- trying to actually merge the two repos together actually so it's taking a bit of time.

**Comment by joelgriffith** [comment]
This is now available in v2! The only difference is it is now available at http://localhost:3000/debugger/
