### ISSUE TITLE
blockAds doesn't work? Is there any way to insert custom uBlock rules into an existing docker container/image? 

### ISSUE THREAD

**Issue by iG8R** [browserless/browserless#3946]
**Describe the bug**
blockAds doesn't work on many sites despite being enabled.
It seems it lacks rules.
Is there any way to insert custom uBlock rules into an existing docker container/image? 

**To Reproduce**

1. Go to https://3dnews.ru/news or https://amedia.site, for example.
2. Behold ads.

**Expected behavior**
All ads should be cut.

**Screenshots**
![image](https://github.com/browserless/browserless/assets/11407417/365b33d1-95aa-4123-a0a0-d373e2615ba6)
![image](https://github.com/browserless/browserless/assets/11407417/f717ec54-8fee-4721-820a-c210bfa9c930)

**Desktop (please complete the following information):**

- Microsoft Windows [Version 10.0.19045.2673]
- Firefox 123.0.1 (64-bit)
- Chrome 122.0.6261.129 (Official Build) (64-bit)
- browserless/chrome:latest c6321df7e37587259bb2c5a334f5d6579dde0f4372e7ad4a13aadb066b493f92

**Comment by joelgriffith** [comment]
`browserless/chrome:latest` is the legacy V1 version which only can block certain network ad requests. Have you tried with V2?
