### ISSUE TITLE
Docker arm64 was working till jan 2024 end now no docker image for arm64

### ISSUE THREAD

**Issue by geminigeek** [browserless/browserless#3958]
**Describe the bug**
i have a docker container browserless v2 running on my raspberry Pi 4GB , just today i tried to install in my another PI 4 , now there is no image for this ?

here is the message 
```
 docker pull ghcr.io/browserless/chrome
Using default tag: latest
latest: Pulling from browserless/chrome
no matching manifest for linux/arm64/v8 in the manifest list entries

```

docker image from my working setup

```
root@Pi4-4GB:~# docker images
REPOSITORY                      TAG       IMAGE ID       CREATED        SIZE
ghcr.io/browserless/chrome      latest    8087bee123ce   7 weeks ago    2.95GB

```

**Expected behavior**
should work on another similar device 

**Desktop (please complete the following information):**
pi where its not working
```
root@Pi4-2GB:~/browserless-docker# uname -a
Linux Pi4-2GB 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux
```
pi on which working 
```
root@Pi4-4GB:~# uname -a
Linux Pi4-4GB 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux
```
similar to https://github.com/browserless/browserless/issues/3914

**Comment by joelgriffith** [comment]
Thanks for reporting -- this is unfortunately the case with `chrome` as there is no arm64 build of chrome proper atm. What you're likely after is the `chromium` version and not the `chrome` version, which we recently changed to capture their differences.
