### ISSUE TITLE
V2 cannot use proxy

### ISSUE THREAD

**Issue by muamua33** [browserless/browserless#3959]
url
```
http://localhost:3000/function?token=6R0W53R135510&--proxy-server=http://x.x.x.x:x
```
error
```
browserless.io:http:function.post error: Failed to load resource: the server responded with a status of 502 (Bad Gateway) +0ms

browserless.io:http:function.post error: WebSocket connection to 'ws://0.0.0.0:3000/devtools/browser/6dfd9ff7-d212-4d13-9b5a-b4152af02e61?token=6R0W53R135510' failed: Establishing a tunnel via proxy server failed. +187ms

browserless.io:http:function.post Error running code: Event: Event +1ms
```

**Comment by joelgriffith** [comment]
Sadly this isn't quite enough to diagnose this issue. Does your code work without the proxy argument?

**Comment by joelgriffith** [comment]
OK, how are you authorizing with the proxy? By IP address?

**Comment by joelgriffith** [comment]
Nice, what's the docker env variables you're using? Could you set `DEBUG=*` and post the output here (as well as your enviroment variables)?

**Comment by Ehsan-U** [comment]
Proxy argument has been removed in the V2 browserless, only option to use proxies is their paid residential service.
