### ISSUE TITLE
SyntaxError: Invalid URL:  "=wss://" inside railway service

### ISSUE THREAD

**Issue by mohammed5420** [browserless/browserless#3962]
**Describe the bug**
I have a project that uses Puppeteer and Browserless it works fine on my computer but when I deploy my project to railway I get this error
`
SyntaxError: Invalid URL:=wss://browserless-production-9ff1.up.railway.app
`
**To Reproduce**

1. Clone  'git@github.com:mohammed5420/designbot.git'
2. Add environment variables from the .env.example
3. Run the app on railway

**Expected behavior**
My should work fine after deploying to Railway

**Desktop (please complete the following information):**

- OS: [Ubuntu Linux]
- Browser [chrome]
- Version [22.04]

**Comment by joelgriffith** [comment]
Sorry can't test on railway, seems like a potential issue with that since all of our automated tests utilize this protocol you're describing.
