### ISSUE TITLE
Please update version of serialize-javascript in use by image dependencies

### ISSUE THREAD

**Issue by russell-maz** [browserless/browserless#4008]
**Describe the bug**
The browserless container has `mocha` as a dependecy.  `Mocha` depends on `serialize-javascript` version `6.0.0`. There is a new version of `serialize-javascript` that addresses a vulnerability that appeared in our AWS container registry. 

https://security.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-6147607

**To Reproduce**

1. Build latest container 
1. sh into container shell
1. Run ` npm ls serialize-javascript`
```
@browserless.io/browserless@2.8.0 /usr/src/app
└─┬ mocha@10.4.0
  └── serialize-javascript@6.0.0
```

**Expected behavior**
Can we bump the version of `serialize-javascript` being used by depdencies to `6.0.2`

**Screenshots**
![image](https://github.com/browserless/browserless/assets/101345328/e34dbe05-fdb1-40f8-96c6-8aa38d93f974)
![image](https://github.com/browserless/browserless/assets/101345328/3b56f469-838c-43b2-b25a-3e9e0868a15e)

**Comment by joelgriffith** [comment]
Once https://github.com/mochajs/mocha/issues/5109 is fixed then we can get that fix internally. This dependency shouldn't be present or used in production systems and is only used during tests. Can you verify that this package isn't present in your container?

**Comment by russell-maz** [comment]
Hi @joelgriffith 

You actually raised a good question. I need to check something in the container. THis may not be for you to resolve. I will revert back shortly

Russell

**Comment by russell-maz** [comment]
Closing this story, the issue is actually originating from a repo i push into my docker container, not your image. Apologies.
