### ISSUE TITLE
Can I set up a header browser after connecting?

### ISSUE THREAD

**Issue by bbhxwl** [browserless/browserless#4016]
Can I set up a header browser after connecting?

**Comment by joelgriffith** [comment]
Not sure I follow -- did you _not_ want headless?

**Comment by bbhxwl** [comment]
> Not sure I follow -- did you _not_ want headless?

The server has no head, I want to show it when the client connects

**Comment by joelgriffith** [comment]
You'll need to use something to stream screenshots or screencasting data back as we don't yet have a way to remotely watch the browser yet in V2.
