### ISSUE TITLE
Browserless Chromium through Docker 2.8.0 tag - Live debugger - ignoreHTTPSErrors invalid parameter

### ISSUE THREAD

**Issue by AndreasA** [browserless/browserless#4020]
**Describe the bug**
When using latest (2.8.0) version of browserless chromium and try to connect to it through the live debugger https://chrome.browserless.io/ and enable the ignore https errors feature, it fails to connect.
<img width="391" alt="image" src="https://github.com/browserless/browserless/assets/1383094/e5a2f2af-c4da-44c7-8de3-a76a23e2ee8a">

The reason is that it adds `?ignoreHTTPSErrors` to the socket URL. However, that socket URL seems to be invalid now and connecting fails. Same for other libraries when using that parameter to connect.

What seems to work correctly is to use the following parameters now: `?launch={"args":["--ignore-certificate-errors"]}`.

Not sure, if the error is in the live debugger or in the image that ignoreHTTPSErrors fails. 
If the error is in the live debugger, than https://github.com/browserless/browserless/blob/main/MIGRATION-2.0.md#removed-parameters-no-replacements is aa bit misleading as well.

**Comment by joelgriffith** [comment]
Yup, we're working on porting the debugger into V2 and including it in this repo, which will mean fixing things like this. Thanks for raising this!

**Comment by andyMrtnzP** [comment]
Actually, the error came from both parts: an outdated debugger and v2 not parsing the `ignoreHTTPSErrors` argument: https://github.com/browserless/browserless/blob/main/src/shim.ts#L17

We're working on fixing this one, should be trivial to solve

**Comment by AndreasA** [comment]
@andyMrtnzP Just wondering but does the parameter `ignoreHTTPSErrors` still work again with 2.14.0 or newer?
