### ISSUE TITLE
Can't update from 2.20-5

### ISSUE THREAD

**Issue by starman2k01** [browserless/browserless#4026]
**Describe the bug**
Home Assistant finds your code and installs 2.2.0-5. But your changelog says you've moved on to 2.8.0
How can I get HA to update to latest?

_If your having issues with a particular site or being bot-blocked, then it's
not an issue with this repo. Please send us an email at support@browserless.io._

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joelgriffith** [comment]
That's probably something you'll have to follow up with on the Home Assistant folks with as we don't directly control what version they're using.

**Comment by starman2k01** [comment]
I'm told it's because browserless hasn't been updated for ARM chips (like the ubiquitous RPi that Home Assistant uses.
Any chance this can be updated for ARM?
