### ISSUE TITLE
I'm using Puppeteer to connect to Browserless for screen recording, but I'm unable to capture the audio stream

### ISSUE THREAD

**Issue by hfmvin** [browserless/browserless#4060]
I'm using Puppeteer to connect to Browserless for screen recording, but I'm unable to capture the audio stream

**Comment by joelgriffith** [comment]
Check with puppeteer but I don't think audio is supported just yet in the libraries/chrome

**Comment by hfmvin** [comment]
Using Puppeteer to launch a headless Chrome locally for recording  audio is ok, but when connecting to Browserless, audio recording is not working
