### ISSUE TITLE
Selenium wire support or network interception ?

### ISSUE THREAD

**Issue by Gby56** [browserless/browserless#4069]
This is a quick question regarding the browserless-hosted usage.

I'm trying to capture all requests made by the remote chrome, so I used selenium wire locally using the browserless docker image.
It works, but I'm not sure this is supported by your remote chrome as a service ?

AFAIK selenium wire injects a local proxy to capture everything, so I assume I would have to expose that proxy so it can work ?
Do you recommend using playwright instead ?

**Comment by joelgriffith** [comment]
Aside from V1, where we support webdriver/HTTP-based-interface, we're awaiting further stability and adoption of the new BiDi protocol to re-enable Selenium support again.

Given that, if this is a relatively new project I'd recommend playwright at this time!
