### ISSUE TITLE
Enable GPU acceleration

### ISSUE THREAD

**Issue by saadbahir** [browserless/browserless#4092]
**Describe the bug**
I followed part of the documentation [here](https://www.browserless.io/blog/browserless-gpu-instances)

and I used the following default args 
```
  DEFAULT_LAUNCH_ARGS: [
    '--disable-web-security',
    '--use-gl=angle',
    '--use-angle=gl',
    '--enable-unsafe-webgpu'
  ],
```

when I launch a chrome instance, the GPU args are correctly attached
```
2024-06-06T06:57:07.899Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--enable-logging",
    "--v1=1",
    "--disable-dev-shm-usage",
    "--no-first-run",
    "--disable-web-security",
    "--use-gl=angle",
    "--use-angle=gl",
    "--enable-unsafe-webgpu",
    "--remote-debugging-port=44251",
    "--user-data-dir=/tmp/browserless-data-dir-2XjIGx"
  ],
```

but when I open chrome://gpu, there is no GPU enabled

> **Graphics Feature Status**
> • Canvas: Software only, hardware acceleration unavailable
> • Canvas out-of-process rasterization: Disabled
> • Direct Rendering Display Compositor: Disabled
> • Compositing: Software only. Hardware acceleration disabled
> • Multiple Raster Threads: Enabled
> • OpenGL: Unavailable
> • Rasterization: Unavailable
> • Raw Draw: Disabled
> • Video Decode: Unavailable
> • Video Encode: Software only. Hardware acceleration disabled
> • Vulkan: Disabled
> • WebGL: Unavailable
> • WebGL2: Unavailable
> • WebGPU: Software only, hardware acceleration unavailable

![gpu-browserless](https://github.com/browserless/browserless/assets/115225167/99dd0625-3f37-46d0-a03f-a02a0d612250)

**Additional context**
I deployed the following image `browserless/chrome:1.59.0-puppeteer-20.2.1` on Amazon Linux G4 instance with Tesla T4 

and I have a GPU on it
```
nvidia-smi
Wed Jun  5 22:52:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P8              15W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

Am I doing anything wrong here? 
Should I rebuild the image with cuda?

**Comment by Adriansillo** [comment]
To use Nvidia GPU you need to do some extra steps 
* install required packages, next line should work for debian based OS
```shell
apt install awscli gcc make pkg-config xserver-xorg-core x11-xserver-utils libglvnd-dev libvulkan1 -y
```
* [Install NVIDIA Driver](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html#public-nvidia-driver)
* [Install NVIDIA container toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
* [Configure NVIDIA runtime for docker](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker)
* Configure Xorg server 
Create a file `/etc/X11/xorg.conf` with your configuration i use this config 
```
Section "ServerLayout"
        Identifier     "X.org Configured"
        Screen      0  "Screen0" 0 0
        InputDevice    "Mouse0" "CorePointer"
        InputDevice    "Keyboard0" "CoreKeyboard"
EndSection
 
Section "Files"
        ModulePath   "/usr/lib/xorg/modules"
        FontPath     "catalogue:/etc/X11/fontpath.d"
        FontPath     "built-ins"
EndSection
 
Section "Module"
        Load  "glx"
EndSection
 
Section "InputDevice"
        Identifier  "Keyboard0"
        Driver      "kbd"
EndSection
 
Section "InputDevice"
        Identifier  "Mouse0"
        Driver      "mouse"
        Option      "Protocol" "auto"
        Option      "Device" "/dev/input/mice"
        Option      "ZAxisMapping" "4 5 6 7"
EndSection
 
Section "Monitor"
        Identifier   "Monitor0"
        VendorName   "Monitor Vendor"
        ModelName    "Monitor Model"
        Modeline "3840x2160_60.00"  712.34  3840 4152 4576 5312  2160 2161 2164 2235  -HSync +Vsync
EndSection

 
Section "Device"
        Identifier  "Card0"
        Driver      "nvidia"
        Option "ConnectToAcpid" "0"
        BusID       "PCI:0:30:0"
EndSection
 
Section "Screen"
        Identifier "Screen0"
        Device     "Card0"
        Monitor    "Monitor0"
        SubSection "Display"
                Viewport   0 0
                Depth     24
        Modes    "2560x1600"
        EndSubSection
EndSection
```
* Run Xorg server
```shell
X &
```

* run your container 
```shell
docker run \
  -d \
  -p 3000:3000 \
  -e 'NVIDIA_DRIVER_CAPABILITIES=all'\
  -e 'NVIDIA_VISIBLE_DEVICES=all'\
  -e 'DISPLAY=:0' \
  -v /tmp:/tmp \
  --privileged \
  browserless/chrome:1-puppeteer-21.3.6
```

There are some versions of chromium which does not identify the gpu when they run in a container, i have been using this image `browserless/chrome:1-puppeteer-21.3.6` for a while, it works fine.

**Comment by saadbahir** [comment]
Thank you @Adriansillo !

So a few notes:

- I was able to get it working without `Xorg` by adding `apt-get install -y vulkan-tools libnvidia-gl-525`
- Chrome needs to have these launch args
```
["--disable-web-security", "--use-angle=vulkan", "--enable-unsafe-webgpu", "--headless=new", "--enable-features=Vulkan,UseSkiaRenderer", "--ignore-gpu-blocklist"]
```
If you add `"--disable-vulkan-surface"` it will enable `Vulkan` but unsure why


- In regards to `browserless/chrome:1-puppeteer-21.3.6` I noticed that the visuals quality is noticeably worse. I couldn't quite quantify it but I compared the screenshot visuals between `browserless/chrome:1-puppeteer-21.3.6` and `browserless/chrome:1.59.0-puppeteer-20.2.1` and the latter provides much better quality 

I am not sure what this means. Maybe I didn't correctly configure `browserless/chrome:1-puppeteer-21.3.6` but the screenshot quality is really bad

**Comment by Adriansillo** [comment]
Thanks @saadbahir for those notes, happy to hear you could make it work
