### ISSUE TITLE
Hope the API supports multiple tabs

### ISSUE THREAD

**Issue by meteor-nb** [browserless/browserless#4095]
**Is your feature request related to a problem? Please describe.**
The current use of HTTP API to crawl content is too slow in response and has limited concurrency

**Describe the solution you'd like**
I hope to use multiple tabs in each session to increase concurrency, rather than adding browsers to increase concurrency; For example, one session can open ten tabs, and ten sessions can achieve 100 concurrency, and the response time for creating tabs is faster than opening a browser.
I hope to customize this option in the "/content" API

**Comment by andyMrtnzP** [comment]
A workaround you can do is using the [`/function` API](https://docs.browserless.io/HTTP-APIs/function), since it gives full access to the Puppeteer page and thus the browser. You can have some code like this:

```js
export default async function ({ context, page }) {
  const browser = await page.browser();
  const promises = Array(context.len).fill(0).map(async () => {
    const page = await browser.newPage();
    await page.goto(context.url);
    const content = await page.content();
    return content;
  });

  const contents = await Promise.all(promises);
  return contents;
}
```

And then run it in a cURL request sending a JSON payload:

```json
{
  "code": "export default async function({context:a,page:t}){let e=await t.browser(),l=Array(a.len).fill(0).map(async()=>{let t=await e.newPage();await t.goto(a.url);let l=await t.content();return l}),n=await Promise.all(l);return n};",
  "context": {
    "len": 10,
    "url": "https://example.com/"
  }
}
```

**Comment by joelgriffith** [comment]
Going to close this for now since there is a workaround!

**Comment by meteor-nb** [comment]
> A workaround you can do is using the [`/function` API](https://docs.browserless.io/HTTP-APIs/function), since it gives full access to the Puppeteer page and thus the browser. You can have some code like this:您可以使用 `/function` API来解决这个问题，因为它可以完全访问Puppeteer页面和浏览器。你可以有这样的代码：
> 
> ```js
> export default async function ({ context, page }) {
>   const browser = await page.browser();
>   const promises = Array(context.len).fill(0).map(async () => {
>     const page = await browser.newPage();
>     await page.goto(context.url);
>     const content = await page.content();
>     return content;
>   });
> 
>   const contents = await Promise.all(promises);
>   return contents;
> }
> ```
> 
> And then run it in a cURL request sending a JSON payload:然后在cURL请求中运行它，发送JSON负载：
> 
> ```json
> {
>   "code": "export default async function({context:a,page:t}){let e=await t.browser(),l=Array(a.len).fill(0).map(async()=>{let t=await e.newPage();await t.goto(a.url);let l=await t.content();return l}),n=await Promise.all(l);return n};",
>   "context": {
>     "len": 10,
>     "url": "https://example.com/"
>   }
> }
> ```

Thanks for the suggestion, but this is not the effect I want, this `/Function API` is slow on every request, what I need is something like a [Splash](https://github.com/scrapinghub/splash) that is offered to `Scrapy` to use!
Right now the `/content API` gets the job done, but it's too slow per request for it, so I think it could be speeded up by opening more tabs!
