### ISSUE TITLE
Cache fonts?

### ISSUE THREAD

**Issue by carstenblt** [browserless/browserless#4112]
I am using browserless to create PDFs.

It seems that the data-dir is deleted after every request, which would result in a lot of requests to download fonts. Can this behaviour be changed?

**Comment by joelgriffith** [comment]
You can specify a cache if you'd like with this parameter: https://docs.browserless.io/open-api#tag/Browser-REST-APIs/paths/~1chrome~1pdf/post (under the "launch" parameter and then the "userDataDir" param

**Comment by carstenblt** [comment]
@joelgriffith Thank you for the answer! Unfortunately this will fail if you have concurrent requests.

```
[8595:8595:0626/060842.443701:ERROR:process_singleton_posix.cc(335)] Failed to create /tmp/cach-dir/SingletonLock: File exists (17)
```
