### ISSUE TITLE
Request timeout when sending many requests sequentially

### ISSUE THREAD

**Issue by carstenblt** [browserless/browserless#4113]
**Describe the bug**
When sending HTML to chromium to render PDFs, I will get "Request has timed out" errors after a while.

**To Reproduce**
Send HTML to the /pdf endpoint like this:

```
await fetch(
      `${process.env.PDF_SERVER}/pdf?token=${process.env.PDF_SERVER_AUTH}`,
      {
        headers: { "Content-Type": "application/json" },
        method: "POST",
        body: JSON.stringify({
          html,
          gotoOptions: {
            waitUntil: "networkidle0",
          },
          options: { format: "A4" },
        }),
      },
    )
```

I send about 50 of those requests, one after each other. That means I really await the result before I send a new request. No concurrency here.

Some of these requests will fail with the mentioned error, usually starting after about 20.

**Expected behavior**
All PDFs should render correctly.

**Additional context**
Adding a 10 second delay between requests seems to solve the issue.

Running ghcr.io/browserless/chromium:v2.13.0 with 2 GB RAM and CONCURRENT=2

**Comment by joelgriffith** [comment]
Unfortunately PDF rendering requires quite a bit of RAM, and there’s a second or two of process still running after sending the response back (hence why your delay fixes the problem). Seems like a larger instance will likely fix your issue
