### ISSUE TITLE
function api can not use proxy

### ISSUE THREAD

**Issue by zscumt123** [browserless/browserless#4152]
**Describe the bug**
my url 
`http://localhost:3006/chromium/function?launch=%7B%22args%22%3A%5B%22--proxy-server%3Dhttp%3A%2F%2F192.168.4.40%3A8001%22%5D%7D`
but proxy is invalid

**Screenshots**
<img width="1627" alt="image" src="https://github.com/browserless/browserless/assets/17904663/69f9c5ad-f154-4b86-8415-39d1e046c110">

**Comment by zscumt123** [comment]
but  /content api and /scrape api is ok

**Comment by joelgriffith** [comment]
This should be fixed now in more recent releases.
