### ISSUE TITLE
Cannot connect via CDP using playwright (python)

### ISSUE THREAD

**Issue by TheOneValen** [browserless/browserless#4160]
**Describe the bug**
Cannot connect via CDP using playwright (python)

**To Reproduce**

```
    p = sync_playwright().start()
    browser = p.chromium.connect_over_cdp("ws://browserless:3000/chromium/playwright?&token=[redacted]&headless=false")
```

results in 

`Error: BrowserType.connect_over_cdp: Protocol error (Browser.getVersion): undefined`

**Expected behavior**
Connection established.

**Additional context**
Selfhosted Browserless 2.15.0

**Comment by joelgriffith** [comment]
That path `ws://browserless:3000/chromium/playwright?&token=[redacted]&headless=false` is meant for CDP Playwright _non CDP_ connections (supports playwrights internal protocol). You can use the following URL for that:

```
ws://browserless:3000/chromium?&token=[redacted]&headless=false
```
