### ISSUE TITLE
can we post ts to the `/function` endpoint ?

### ISSUE THREAD

**Issue by chinafzy** [browserless/browserless#4162]
Can we post typescript codes to the `/function` endpoint ?
Thanks a lot!

**Comment by andyMrtnzP** [comment]
Unfortunately, no. The function runs inside a browser, thus the code can only be standard JS/ECMAScript code :/. For more info, you can check out [our official docs](https://docs.browserless.io/HTTP-APIs/function)

**Comment by chinafzy** [comment]
Thanks for the reply.
Since we can post ts code in the debugger, why not copy this wonderful feature to the `/function` endpoint?

**Comment by chinafzy** [comment]
> Unfortunately, no. The function runs inside a browser, thus the code can only be standard JS/ECMAScript code :/. For more info, you can check out [our official docs](https://docs.browserless.io/HTTP-APIs/function)

Thanks for the reply.
Since we can post ts code in the debugger, why not copy this wonderful feature to the /function endpoint?
