### ISSUE TITLE
Can't increase window-size when using HTTP API for screenshot

### ISSUE THREAD

**Issue by tjfoth** [browserless/browserless#4178]
**Describe the bug**
I am making HTTP API calls from Node Red and trying to increase the window-size beyond 800x600.

http://192.168.1.194:3030/screenshot?token=nnnnnn&--window-size=1920,1080
mentioned elsewhere does not work.

Neither does &launch={"args":["--window-size=1920,1080"]} or args, or various forms of launch and args in the JSON request.

It is either ignored, or in the case of attempts using JSON, I get "Couldn't parse JSON body"

Raspbian OS Bookworm
Arm64 Docker using the latest v2 image.

I'm not super great at ready Javascript, but I can't find anyplace where it is explicitly supported.

**Comment by andyMrtnzP** [comment]
It's really tricky to set the window size using Puppeteer. Sadly this is a known bug (https://github.com/puppeteer/puppeteer/issues/1910), where it's possible to set the viewport size and window size, but screen resolution, window bounds, and other values related to the screen aren't changed and get the Chromium defaults. Although checking the log, you'll see that the browser got the args.

I'm curious about the error message you are getting. Can you share a snippet/request?

**Comment by tjfoth** [comment]
If I pass this JSON via an HTTP request:
{"url": "
https://storage.googleapis.com/rss-news-store.appspot.com/radar-html/rainviewerClose.html",

 "gotoOptions": { "waitUntil": "networkidle2" },
 "args": [     "--window-size=1920,1080",     "--lang=en-US"   ] }

Which is implied in the docs here: https://docs.browserless.io/chrome-flags/

[image: image.png]

I receive this message back:

POST Body validation failed: "args" is not allowed

Somewhere I read this should work:

{"url": "
https://storage.googleapis.com/rss-news-store.appspot.com/radar-html/rainviewerClose.html
",
  "gotoOptions": { "waitUntil": "networkidle2" },
   "launch": {"args":["--window-size=1920,1080"]} }

That yielded: POST Body validation failed: "launch" is not allowed

Unfortunately, I can't reproduce the JSON structure that caused the "Couldn't
parse JSON body" message.  Being a developer, I know better that I SHOULD
have captured the environment that yielded the message, but it was late at
night, I was frustrated... my bad.

All attempts to pass window-size with the POST url are simply ignored with
no error message.

Thanks for so quickly jumping on this.  I'm glad you said this is a tricky
issue and a known bug.

That being said, I'd even be more glad if you had an answer (as I suspect a
lot of other people would, too!)... but, being a developer, I know some
bugs don't have ready answers.

---
Tom Foth
***@***.***
***@***.***

**Comment by tjfoth** [comment]
That did it!  Thanks so MUCH!

---
Tom Foth
***@***.***
***@***.***

**Comment by joelgriffith** [comment]
Thanks @hdformat , that is indeed likely the issue. Puppeteer and most libraries have window size and page size as separate concepts, so things like this are somewhat common unfortunately. Closing
