### ISSUE TITLE
content doesn't respect defaultViewport or --window-size

### ISSUE THREAD

**Issue by jslay88** [browserless/browserless#4217]
**Describe the bug**

**To Reproduce**

* Launch browserless container
* Launch changedection.io container pointing to browserless WS
* Try get get page, preview, and visual filter selector.
* Verify the request defaultViewport and args are accepted by looking at browserless logs

Using changedetection.io container using browerless container with playwright, and setting defaultViewport for launch on WS connection, the page renders the correct width, but the content is 800px.

```
launch={"defaultViewport":{"height":1440,"width":2560},"headless":false,"stealth":true,"args":["--window-size=2560,1440"]}
```

![image](https://github.com/user-attachments/assets/d808fb91-9bcd-40b5-b6ce-e2da53a0895b)

When using the visual filter selector, it does seem like the content gets highlighted as if it was the correct width

![image](https://github.com/user-attachments/assets/7d1486b6-5271-4ba6-a3ea-596f86318ac8)

Not sure if the fault is on browserless or changedetection.io 

**Expected behavior**
Content to stretch the width of the page as it would on desktop.

https://github.com/dgtlmoon/changedetection.io/issues/2556

**Comment by jslay88** [comment]
Looks to be a _similar_ issue https://github.com/dgtlmoon/changedetection.io/discussions/2541

**Comment by dgtlmoon** [comment]
@jslay88 can you close this please? this is not in any way a problem with browserless and we dont use browserless (see our `docker-compose.yml` )

**Comment by jslay88** [comment]
How are we sure where the problem lies? What evidence do we have that it isn't one or the other?

**Comment by joelgriffith** [comment]
Have you tried directly using our APIs for that? https://docs.browserless.io/open-api#tag/Browser-REST-APIs/paths/~1chrome~1content/post
