### ISSUE TITLE
Application logs tokens in the open

### ISSUE THREAD

**Issue by moltar** [browserless/browserless#4221]
**Describe the bug**

During startup many lines with the secret token are logged.

_If your having issues with a particular site or being bot-blocked, then it's

N/A

**To Reproduce**

Start form a Docker image and observe the token leaking.

**Expected behavior**

Not to log token.

**Screenshots**

![screenshot-20240812T170916-g7Cwg6br@2x](https://github.com/user-attachments/assets/94246cf2-da09-4c3f-855d-f8054bfa2c32)

![screenshot-20240812T170912-RmtgagM3@2x](https://github.com/user-attachments/assets/ea55dc4d-749e-4314-a2e0-f85041caac18)

**Desktop (please complete the following information):**

- OS: Linux
- Browser [e.g. chrome, safari]: chrome
- Version [e.g. 22]: latest

**Smartphone (please complete the following information):**

**Additional context**

Running from a Docker image.

**Comment by joelgriffith** [comment]
Thanks for raising. I think we assumed that access to logs is generally restricted. Do you have thoughts otherwise?

**Comment by moltar** [comment]
Yes, that's true. But it's still a best practice to never log secret values.

Logs can be shipped somewhere, ingested, archived, etc. So the attack vector increases.

**Comment by joelgriffith** [comment]
Fixed in https://github.com/browserless/browserless/pull/4222
