### ISSUE TITLE
Unblock API returning 404 error

### ISSUE THREAD

**Issue by joelwright-dev** [browserless/browserless#4226]
**Describe the bug**
I'm trying to use the unblock API to get a browserWSEndpoint but just get a 404 error.

**To Reproduce**

1. Run the following code
```
const response = await fetch(`https://production-sfo.browserless.io/unblock?token=${process.env.BROWSERLESS_API_KEY}`, {
  method: "POST",
  body: JSON.stringify({
      url: startUrl,
      browserWSEndpoint: true,
      cookies: true,
      content: false,
      screenshot: false,
      ttl: 10
  })
  }).then((r) => {
  if(r.ok) {
      return r.json()
  }
  console.log(r)
  throw new Error(r.status)
  })
```
2. Get 404 error

**Expected behavior**
A 200 response.

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 127.0.6533.99

**Additional context**
I have the starter plan but from my understanding this API is available to all users?

**Comment by joelgriffith** [comment]
Hey there, thanks for raising. Our APIs are fairly strict, so you'll need a `Content-Type` header in order for it to properly be routed:

```await fetch(`https://production-sfo.browserless.io/unblock?token=${process.env.BROWSERLESS_API_KEY}`, {
  method: "POST",
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
      url: startUrl,
      browserWSEndpoint: true,
      cookies: true,
      content: false,
      screenshot: false,
      ttl: 10
  })
  })```
