### ISSUE TITLE
Can you add sdk of https://github.com/go-rod/rod

### ISSUE THREAD

**Issue by feeops** [browserless/browserless#4227]
Can you add sdk of 

https://github.com/go-rod/rod

go-rod is easier than chromecdp

**Comment by joelgriffith** [comment]
@feeops not an expert in go, is there a way to connect to a remote browser with that library?

**Comment by feeops** [comment]
> @feeops not an expert in go, is there a way to connect to a remote browser with that library?

Yes,it is.

**Comment by joelgriffith** [comment]
Nice! In that case then it should be fairly straightforward depending on how they interact with Chrome/CDP. I did look quickly over their docs and didn't see a way to connect, if you could point that out for me then I'd be happy to take it from there.

**Comment by andyMrtnzP** [comment]
As for the Rod docs, they do [support remote connections](https://go-rod.github.io/#/custom-launch?id=connect-to-an-running-browser). Here's a working example:

```go
package main

import "github.com/go-rod/rod"

func main() {
	//or "wss://chrome.browserless.io/?token=GOES-HERE"
	u := "ws://localhost:3000/?token=6R0W53R135510"
	page := rod.New().ControlURL(u).MustConnect().MustPage("https://example.com")
	page.MustWaitStable().MustScreenshot("a.png")
}

```

**Comment by joelgriffith** [comment]
Awesome! Going to close for now but will add to our docsite. Thanks for snippet!

**Comment by jackHedaya** [comment]
Hi!
I think there may be a misalignment between the go rod websocket and the browser less web socket. When a 408 is returned, Rod panics because it is unable to unmarshal the JSON. I'm unsure if this is a Rod issue or a Browserless issue; can you please confirm?

Here is the panicking line:
https://github.com/go-rod/rod/blob/main/lib/cdp/client.go#L148
