### ISSUE TITLE
Docker : /config & /json/version Not Found

### ISSUE THREAD

**Issue by marc-polizzi** [browserless/browserless#4234]
I'm evaluating the latest Docker (chromium) and I've been able to generate a PDF but when trying to access : 

```
/config
/json/version
```

the logs are saying `No matching HTTP route handler...`.

![browerless](https://github.com/user-attachments/assets/2666a779-7f7a-403b-aa12-cddcd1f77e87)

Am I missing something ?

**Comment by joelgriffith** [comment]
Since they're JSON APIs you'll need a `Content-Type` headers. This does come up quite often so thinking we will fix it since it's a non-intuitive fix

**Comment by marc-polizzi** [comment]
Do you mean : 

```
curl -X POST http://localhost:3000/config?token=MARC -H 'Content-Type: application/json'
```

Same response : Not found.

Sending that request, I realized that I should perhaps use a GET : 

```
curl -X GET http://localhost:3000/config?token=MARC
```

And then it worked. Silly me ;-)

**Comment by joelgriffith** [comment]
Was just going to ask that same question! Anyways, going to close for now and see if we can't figure out a better way to handle content-types in the future.
