### ISSUE TITLE
Puppeteer PDF generation printBackground

### ISSUE THREAD

**Issue by julian-ladjani** [browserless/browserless#4251]
Hello,
I generate a PDF with puppeteer in front of another pdf, since I updated from chrome:v2.8.0 to chrome:v2.17.1 (also tested with v2.18.0) I have a problem with the pdf generated with puppeteer , printBackground = false, doesn't seem to work

**Comment by joelgriffith** [comment]
Are you able to share some code and resulting screenshots?

**Comment by julian-ladjani** [comment]
We found the problem:
```
html {
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}
```
Make this problem on newer chrome version, I close this issue, thank you
