### ISSUE TITLE
Puppeteer can screenshot h265-web-picture，but broswerless cant's show h265 content

### ISSUE THREAD

**Issue by StarCsu** [browserless/browserless#4264]
**Describe the bug**
On the Mac M1 system, I compiled Browserless without using Docker in my local environment. I ran Browserless and Puppet instances, and Puppet instance rendered H265 content, but Browserless did not;

**To Reproduce**

1. puppeteer code
```
import puppeteer from 'puppeteer';

(async () => {
  // 启动浏览器
  const browser = await puppeteer.launch();
  const page = await browser.newPage();


  // Set screen size.
  await page.setViewport({width: 1080, height: 1024});

  // 导航到 Google
  await page.goto('https://xxx.cc/?ds=remote-file&ds.url=1bf4ebcbb02b923f.mcap&layout=122&time=2024-03-11T04%3A06%3A59.763716594Z');

  //  查看gpu
  //await page.goto('chrome://gpu/');


  // 等待 3 秒
  await wait(8000);
  // 截取截图并保存
  await page.screenshot({ path: 'local_hviz.png' });

  // 关闭浏览器
  await browser.close();
})();


// 定义一个延迟函数
function wait(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```

2. puppeteer render
screen shot:
![image](https://github.com/user-attachments/assets/81020282-0911-4569-8400-3fa78136e206)

gpu picture :
![local_hviz](https://github.com/user-attachments/assets/acc88c88-3b03-4e9c-8796-f143717bc8de)

3.  browserless code
```
import puppeteer from 'puppeteer';

(async () => {
  // 启动浏览器
  const browser = await puppeteer.connect({
    browserWSEndpoint: 'ws://localhost:3000/?--use-gl=angle&--use-angle=gl',
    DEFAULT_LAUNCH_ARGS: [
      '--disable-web-security',
      '--use-gl=angle',
      '--use-angle=gl',
      '--enable-unsafe-webgpu'
    ],
  });
  
  const page = await browser.newPage();

  // Set screen size.
  await page.setViewport({width: 1080, height: 1024});

  // 导航到 Google
  await page.goto('https://xxx.cc/?ds=remote-file&ds.url=1bf4ebcbb02b923f.mcap&layout=122&time=2024-03-11T04%3A06%3A59.763716594Z');

  //  查看gpu
  //await page.goto('chrome://gpu/');

  // 等待 3 秒
  await wait(8000);
  // 截取截图并保存
  await page.screenshot({ path: 'chrome5.png' });

  // 关闭浏览器
  await browser.close();
})();

// 定义一个延迟函数
function wait(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```
4. broswerless rendar
screenshot:
![image](https://github.com/user-attachments/assets/48b2fcc3-dc1c-4009-86e8-ebbd66ce4ca5)

gpu screenshot
![chrome5](https://github.com/user-attachments/assets/ab289fea-d28c-4cac-b58e-36ff04d8c59a)

**Expected behavior**
In theory, the content rendered by these two should be consistent

**Desktop (please complete the following information):**

- OS: [e.g. mac os m1]
- Browser [e.g. chrome]
- Version [e.g. 128]

**Additional context**
because i don't have xvfb on the mac ststem ,so  i deleted xvfb start code;
![image](https://github.com/user-attachments/assets/e72a7ddf-f75f-4e03-b6bf-0c9bf9dbe305)

**Comment by StarCsu** [comment]
> You'll likely need `ghcr.io/browserless/chrome` instead of `chromium` as there's extra codecs in that build. I'd retry with that docker image but there is a caveat: "chrome" isn't yet available or built for arm64 machines! If you have access to an x86 machine then it'll likely start working

thank you your reply，now i don't use chromium  docker，Docker in Mac cannot use GPU to accelerate H265
；if i only build browserless locally，How should I build it？

**Comment by StarCsu** [comment]
Tomorrow I will use Windows for verification, theoretically there should be no problem here, right？

**Comment by joelgriffith** [comment]
Correct, Windows would be the way to go as there's no Chrome builds for any linux/arm64 platforms as far as I'm aware.

**Comment by StarCsu** [comment]
> Correct, Windows would be the way to go as there's no Chrome builds for any linux/arm64 platforms as far as I'm aware.

After compiling browserless locally on Windows, "npm start" encountered the following error:
```
Unhandled Rejection at: Promise {
"ChromiumCDP"
      at file:///C:/Users/zhihao.yin/work/browserless-main/build/browserless.js:202:23
      at Array.forEach (<anonymous>)
      at Browserless.start (file:///C:/Users/zhihao.yin/work/browserless-main/build/browserless.js:197:19)     
} reason: Error: Couldn't load route "/content?(/),/chromium/content?(/)" due to missing browser binary for "Ch    at Array.forEach (<anonymous>)
```

But I can execute it successfully directly with puppeteer in Windows；

os:Windows10;

**Comment by andyMrtnzP** [comment]
Hey, were you able to try it out?
