### ISSUE TITLE
Stealth do not work

### ISSUE THREAD

**Issue by feeops** [browserless/browserless#4288]
I set Stealth to true

get screenshot of https://bot.sannysoft.com/

![html](https://github.com/user-attachments/assets/218ba8e1-619d-4372-9e67-873ecb7e72df)

It failed

**Comment by joelgriffith** [comment]
Hey there, we simply use the `puppeteer-stealth` package for this and don't necessarily control it. I'd create an issue in that repo as they'll have some ability to fix issues there.
