### ISSUE TITLE
Error while running the  Docker  image in the CI pipeline

### ISSUE THREAD

**Issue by anithaani09** [browserless/browserless#4298]
Facing issue while running the docker image in the CI pipeline

Below the error message saying " src/browsers/cdp-chromium.ts(15,10): error TS2305: Module '"../constants.js"' has no exported member 'liveURLSep'."

![image](https://github.com/user-attachments/assets/d5702ffe-1f1f-44f8-8879-8b509d5d6878)

please Help me out to build the image

**Comment by joelgriffith** [comment]
@anithaani09 that's a somewhat older checkout of the source. Can you merge updates from `main` and try again?

**Comment by anithaani09** [comment]
Thank you for the response!! 

I have tired using the latest updates of main branch and still having the same issue in the pipeline.

![image](https://github.com/user-attachments/assets/a97b4b93-501a-4612-8234-272690949066)

Please help me out. Thank you!!
