### ISSUE TITLE
docs dark mode unreadable

### ISSUE THREAD

**Issue by o-az** [browserless/browserless#4347]
**Describe the bug**

https://docs.browserless.io when you enable dark mode, the text is black and unreadable

![docs browserless io_](https://github.com/user-attachments/assets/6179bf04-9631-4216-bc61-ffe58523d1c0)

_If your having issues with a particular site or being bot-blocked, then it's
not an issue with this repo. Please send us an email at support@browserless.io._

**To Reproduce**

1. Go to https://docs.browserless.io
2. Click on theme toggle
3. See unreadable text

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andyMrtnzP** [comment]
Thanks for raising this one. This was under our radar for a while and the issue prompted us to finally solve it.

It's currently live right now, so we'll close this one for now. Feel free to re-open it if you find anything else. Thanks!
