### ISSUE TITLE
No live debugger avalible in Chromium docker 

### ISSUE THREAD

**Issue by masterwishx** [browserless/browserless#4405]
Using docker in Unraid.
Latest version of [ghcr.io/browserless/chromium](https://github.com/browserless/browserless/pkgs/container/chromium)

when trying to go to debug `http://192.168.0.199:3012/debugger/?token=TOKEN` : 

`browserless.io:error No route or file found for resource GET: /debugger/ +3m`

![image](https://github.com/user-attachments/assets/0853e2ad-b095-48d2-a0f8-01de59859897)

**Comment by masterwishx** [comment]
Found debugger at /debugger but with errors like : 

![image](https://github.com/user-attachments/assets/6a3fd89e-63bd-4e56-a4fc-a95cbfb4e1b3)

**Comment by masterwishx** [comment]
Sorry my bad, debugger was disabled in container env from long time ago when was no debugger at all

**Comment by white0dew** [comment]
> Sorry my bad, debugger was disabled in container env from long time ago when was no debugger at all抱歉，我的错，调试器从很久以前就在容器环境中被禁用，当时根本没有调试器

什么意思呢，是指docker无法使用debugger吗？

**Comment by masterwishx** [comment]
> > Извините, мой плохой, отладчик был отключен в контейнерной среде давным-давно, когда отладчика вообще не было. Извините, 



> > Sorry my bad, debugger was disabled in container env from long time ago when was no debugger at all抱歉，我的错，调试器从很久以前就在容器环境中被禁用，当时根本没有调试器
> 
> 什么意思呢，是指docker无法使用debugger吗？

You need enable it by container variable

**Comment by schunlee** [comment]
> > > Извините, мой плохой, отладчик был отключен в контейнерной среде давным-давно, когда отладчика вообще не было. Извините,
> 
> > > Sorry my bad, debugger was disabled in container env from long time ago when was no debugger at all抱歉，我的错，调试器从很久以前就在容器环境中被禁用，当时根本没有调试器
> > 
> > 
> > 什么意思呢，是指docker无法使用debugger吗？
> 
> You need enable it by container variable

and how to enabled it
