### ISSUE TITLE
Not working on Cloud Run?

### ISSUE THREAD

**Issue by olegkorol** [browserless/browserless#4406]
**Describe the bug**

The v2 application doesn't seem to start on Google Cloud Run.

(v1 works properly)

**To Reproduce**

1. Use `ghcr.io/browserless/chromium:latest` to push an image to Google Artifact Registry (cannot work with ghcr.io directly).
2. Start a Cloud Run service with that image (e.g. `europe-docker.pkg.dev/project/repo/browserless-chromium:latest`), listening on port 3000.
3. It won't start, yielding the following error:
```text
The user-provided container failed to start and listen on the port defined provided by the PORT=3000 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The healtcheck timeout can be extended.
```

Upon further inspection in the logs, the following message can be found:

```text
terminated: Application failed to start: failed to load /usr/src/app/scripts/start.sh: exec format error
```

**Note:**
Locally everything works fine:
```bash
docker run -p 3000:3000 europe-docker.pkg.dev/project/repo/browserless-chromium:latest

# Starts and works as expected
```

**Expected behavior**
I would expect the service to start.

Many thanks in advance!

**Comment by olegkorol** [comment]
Ok, I tried using `ghcr.io/browserless/chrome:latest@sha256:3c86bcc0f0155daeb196ba0baa2db1e5dfc143d90f9c209267113f98f5cba065` instead, and it seems to work.

**Comment by olegkorol** [comment]
Hi @joelgriffith.
The HTML string is 306,633 characters long.

**Comment by joelgriffith** [comment]
Yeah that's not too large of a payload... are you using some kind of library or HTTP REST API?

**Comment by olegkorol** [comment]
Not really.

If I pass e.g. `<h1>Hello!</h1>` as a payload it just works like a charm. If I pass it the 300K+ characters long string it just doesn't work, as described above.

Not sure if relevant, but most of the content of the HTML-string are base64-encoded images.

**Comment by scald** [comment]
@olegkorol thanks for the SHA, that also got me going on cloud run. how much RAM did you assign? I have 2gb and it is handling pretty large html payloads.

**Comment by joelgriffith** [comment]
My guess is that there's a body limit on the cloud-run side?

**Comment by olegkorol** [comment]
Glad it helped, @scald.
I tried assigning different amounts of memory – from 1GB to to 16GB. It always hangs at `setContent()` regardless :/

Not sure about the body limit, @joelgriffith. That shouldn't be an issue.

I'll see if I can find the root cause and post an update here.

**Comment by olegkorol** [comment]
What ended up working for me:

Instead of using `page.setContent()` I switched to `page.goto()`:

```typescript
// [...]
const encodedHtml = encodeURIComponent(htmlString);

const page = await browser.newPage();
await page.goto(`data:text/html,${encodedHtml}`, { waitUntil: 'networkidle2' });
const pdfUint8Array = await page.pdf(pdfConfig);

// [...]
```

This works like a charm on both Cloud Run and Fly.io, using the aforementioned Browserless image: `ghcr.io/browserless/chromium:latest@sha256:b640a6e96e9ef1d27111165582b56940374d35e57610ff42f32473a39f1034a0`

Just for reference: I am using [Deno](https://deno.com/) with [`@astral/astral`](https://github.com/lino-levan/astral).
